apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/urls: '["https://kotori-api-412014849981.us-central1.run.app","https://kotori-api-zlj7skne5a-uc.a.run.app"]'
  labels:
    cloud.googleapis.com/location: us-central1
  name: kotori-api
  namespace: '412014849981'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 530.0.0
        run.googleapis.com/startup-cpu-boost: 'true'
        run.googleapis.com/vpc-access-connector: kotori-connector
        run.googleapis.com/vpc-access-egress: private-ranges-only
      labels:
        client.knative.dev/nonce: eenofgrdjj
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 100
      containers:
      - env:
        - name: CORS_ORIGINS
          value: https://app.kotori.io,https://kotori.io,http://localhost:19000,http://localhost:19006
        - name: LOG_LEVEL
          value: INFO
        - name: NODE_ENV
          value: production
        - name: SAVE_TRANSCRIBE_UPLOADS
          value: '0'
        - name: ENVIRONMENT
          value: production
        - name: database-url
          valueFrom:
            secretKeyRef:
              key: latest
              name: database-url
        - name: secret-key
          valueFrom:
            secretKeyRef:
              key: latest
              name: secret-key
        image: us-central1-docker.pkg.dev/kotori-io/kotori-images/kotori-api:deploy-20250814-120621
        ports:
        - containerPort: 8001
          name: http1
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8001
          timeoutSeconds: 240
      serviceAccountName: kotori-api@kotori-io.iam.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
