# Cloud Build configuration to verify current Alembic revision
# Uses Private Worker Pool and Secret Manager (DATABASE_URL)

steps:
  # Build the backend image (same pattern as run-migrations)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/kotori-io/kotori-images/kotori-api:verify-${SHORT_SHA}'
      - '.'
    dir: 'backend'

  # Run a verification step that prints current Alembic revision
  - name: 'us-central1-docker.pkg.dev/kotori-io/kotori-images/kotori-api:verify-${SHORT_SHA}'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euo pipefail
        cd /app
        if [[ -z "$DATABASE_URL" ]]; then
          echo "DATABASE_URL not set" && exit 1
        fi
        echo "📊 Printing current Alembic revision..."
        alembic current || true
    secretEnv:
      - DATABASE_URL

availableSecrets:
  secretManager:
    - versionName: projects/kotori-io/secrets/database-url/versions/latest
      env: DATABASE_URL

timeout: '600s'
options:
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: projects/kotori-io/locations/us-central1/workerPools/private-pool
  substitution_option: 'ALLOW_LOOSE'


