"""Initial schema with optimized indexes and constraints

Revision ID: 2c88eb7b741c
Revises: 
Create Date: 2025-07-14 00:30:21.807876

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision = '2c88eb7b741c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_name', sa.String(length=100), nullable=False),
    sa.Column('channel_type', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('retry_delay', sa.Integer(), nullable=False),
    sa.Column('rate_limit_count', sa.Integer(), nullable=True),
    sa.Column('rate_limit_window', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_channels_enabled', 'alert_channels', ['enabled'], unique=False)
    op.create_index('idx_alert_channels_type', 'alert_channels', ['channel_type'], unique=False)
    op.create_index(op.f('ix_alert_channels_channel_name'), 'alert_channels', ['channel_name'], unique=True)
    op.create_index(op.f('ix_alert_channels_channel_type'), 'alert_channels', ['channel_type'], unique=False)
    op.create_index(op.f('ix_alert_channels_id'), 'alert_channels', ['id'], unique=False)
    op.create_table('alert_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('condition', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('suppression_duration', sa.Integer(), nullable=False),
    sa.Column('escalation_delay', sa.Integer(), nullable=False),
    sa.Column('delivery_channels', sa.JSON(), nullable=True),
    sa.Column('delivery_config', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_rules_enabled', 'alert_rules', ['enabled'], unique=False)
    op.create_index('idx_alert_rules_severity', 'alert_rules', ['severity'], unique=False)
    op.create_index(op.f('ix_alert_rules_id'), 'alert_rules', ['id'], unique=False)
    op.create_index(op.f('ix_alert_rules_rule_id'), 'alert_rules', ['rule_id'], unique=True)
    op.create_table('monitoring_configuration',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_category', sa.String(length=50), nullable=False),
    sa.Column('config_value', sa.JSON(), nullable=False),
    sa.Column('config_description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config_version', sa.String(length=20), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_monitoring_config_category', 'monitoring_configuration', ['config_category'], unique=False)
    op.create_index('idx_monitoring_config_key', 'monitoring_configuration', ['config_key'], unique=False)
    op.create_index(op.f('ix_monitoring_configuration_config_category'), 'monitoring_configuration', ['config_category'], unique=False)
    op.create_index(op.f('ix_monitoring_configuration_config_key'), 'monitoring_configuration', ['config_key'], unique=True)
    op.create_index(op.f('ix_monitoring_configuration_id'), 'monitoring_configuration', ['id'], unique=False)
    op.create_table('monitoring_dashboards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dashboard_name', sa.String(length=100), nullable=False),
    sa.Column('dashboard_title', sa.String(length=255), nullable=False),
    sa.Column('dashboard_description', sa.Text(), nullable=True),
    sa.Column('dashboard_layout', sa.JSON(), nullable=False),
    sa.Column('dashboard_widgets', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('refresh_interval', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('allowed_users', sa.JSON(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_monitoring_dashboards_active', 'monitoring_dashboards', ['is_active'], unique=False)
    op.create_index('idx_monitoring_dashboards_name', 'monitoring_dashboards', ['dashboard_name'], unique=False)
    op.create_index(op.f('ix_monitoring_dashboards_dashboard_name'), 'monitoring_dashboards', ['dashboard_name'], unique=True)
    op.create_index(op.f('ix_monitoring_dashboards_id'), 'monitoring_dashboards', ['id'], unique=False)
    op.create_table('monitoring_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('metric_source', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('metric_unit', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('dimensions', sa.JSON(), nullable=True),
    sa.Column('threshold_exceeded', sa.Boolean(), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_monitoring_metrics_name_timestamp', 'monitoring_metrics', ['metric_name', 'timestamp'], unique=False)
    op.create_index('idx_monitoring_metrics_source', 'monitoring_metrics', ['metric_source'], unique=False)
    op.create_index('idx_monitoring_metrics_type', 'monitoring_metrics', ['metric_type'], unique=False)
    op.create_index(op.f('ix_monitoring_metrics_id'), 'monitoring_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_monitoring_metrics_metric_name'), 'monitoring_metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_monitoring_metrics_metric_source'), 'monitoring_metrics', ['metric_source'], unique=False)
    op.create_index(op.f('ix_monitoring_metrics_metric_type'), 'monitoring_metrics', ['metric_type'], unique=False)
    op.create_index(op.f('ix_monitoring_metrics_timestamp'), 'monitoring_metrics', ['timestamp'], unique=False)
    op.create_table('opaque_sessions',
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', UUID(), nullable=False),
    sa.Column('tag_id', sa.LargeBinary(length=16), nullable=True),
    sa.Column('session_state', sa.String(length=20), nullable=False),
    sa.Column('session_data', sa.LargeBinary(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('idx_opaque_sessions_expires_at', 'opaque_sessions', ['expires_at'], unique=False)
    op.create_index('idx_opaque_sessions_user_id', 'opaque_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_opaque_sessions_tag_id'), 'opaque_sessions', ['tag_id'], unique=False)
    op.create_index(op.f('ix_opaque_sessions_user_id'), 'opaque_sessions', ['user_id'], unique=False)
    op.create_table('security_alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('detection_rule', sa.String(length=100), nullable=False),
    sa.Column('user_id_hash', sa.String(length=64), nullable=True),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('related_events', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_actions', sa.Text(), nullable=True),
    sa.Column('manual_notes', sa.Text(), nullable=True),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alerts_status_time', 'security_alerts', ['status', 'first_seen'], unique=False)
    op.create_index('idx_alerts_type_severity', 'security_alerts', ['alert_type', 'severity'], unique=False)
    op.create_index('idx_alerts_user_time', 'security_alerts', ['user_id_hash', 'first_seen'], unique=False)
    op.create_index(op.f('ix_security_alerts_alert_type'), 'security_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_security_alerts_correlation_id'), 'security_alerts', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_security_alerts_first_seen'), 'security_alerts', ['first_seen'], unique=False)
    op.create_index(op.f('ix_security_alerts_severity'), 'security_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_security_alerts_status'), 'security_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_security_alerts_user_id_hash'), 'security_alerts', ['user_id_hash'], unique=False)
    op.create_table('security_audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_category', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('user_id_hash', sa.String(length=64), nullable=True),
    sa.Column('session_id_hash', sa.String(length=64), nullable=True),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=True),
    sa.Column('event_data', sa.Text(), nullable=True),
    sa.Column('event_message', sa.String(length=500), nullable=False),
    sa.Column('log_signature', sa.String(length=128), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_category_severity', 'security_audit_logs', ['event_category', 'severity'], unique=False)
    op.create_index('idx_audit_correlation_id', 'security_audit_logs', ['correlation_id'], unique=False)
    op.create_index('idx_audit_event_type_timestamp', 'security_audit_logs', ['event_type', 'timestamp'], unique=False)
    op.create_index('idx_audit_timestamp', 'security_audit_logs', ['timestamp'], unique=False)
    op.create_index('idx_audit_user_timestamp', 'security_audit_logs', ['user_id_hash', 'timestamp'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_correlation_id'), 'security_audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_event_category'), 'security_audit_logs', ['event_category'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_event_type'), 'security_audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_session_id_hash'), 'security_audit_logs', ['session_id_hash'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_severity'), 'security_audit_logs', ['severity'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_timestamp'), 'security_audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_user_id_hash'), 'security_audit_logs', ['user_id_hash'], unique=False)
    op.create_table('security_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_type', sa.String(length=30), nullable=False),
    sa.Column('time_window', sa.String(length=20), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('max_value', sa.Integer(), nullable=True),
    sa.Column('min_value', sa.Integer(), nullable=True),
    sa.Column('avg_value', sa.Integer(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_metrics_name_window', 'security_metrics', ['metric_name', 'window_start'], unique=False)
    op.create_index('idx_metrics_type_time', 'security_metrics', ['metric_type', 'window_start'], unique=False)
    op.create_index(op.f('ix_security_metrics_metric_name'), 'security_metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_security_metrics_window_end'), 'security_metrics', ['window_end'], unique=False)
    op.create_index(op.f('ix_security_metrics_window_start'), 'security_metrics', ['window_start'], unique=False)
    op.create_table('service_health',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('uptime_seconds', sa.Integer(), nullable=True),
    sa.Column('cpu_usage', sa.Float(), nullable=True),
    sa.Column('memory_usage', sa.Float(), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('health_check_passed', sa.Boolean(), nullable=True),
    sa.Column('health_check_message', sa.Text(), nullable=True),
    sa.Column('dependencies_healthy', sa.Boolean(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_service_health_service_timestamp', 'service_health', ['service_name', 'timestamp'], unique=False)
    op.create_index('idx_service_health_status', 'service_health', ['status'], unique=False)
    op.create_index(op.f('ix_service_health_id'), 'service_health', ['id'], unique=False)
    op.create_index(op.f('ix_service_health_service_name'), 'service_health', ['service_name'], unique=False)
    op.create_index(op.f('ix_service_health_status'), 'service_health', ['status'], unique=False)
    op.create_index(op.f('ix_service_health_timestamp'), 'service_health', ['timestamp'], unique=False)
    op.create_table('system_health',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('overall_status', sa.String(length=20), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('cpu_usage', sa.Float(), nullable=True),
    sa.Column('memory_usage', sa.Float(), nullable=True),
    sa.Column('disk_usage', sa.Float(), nullable=True),
    sa.Column('network_usage', sa.Float(), nullable=True),
    sa.Column('active_sessions', sa.Integer(), nullable=True),
    sa.Column('request_rate', sa.Float(), nullable=True),
    sa.Column('error_rate', sa.Float(), nullable=True),
    sa.Column('response_time_p95', sa.Float(), nullable=True),
    sa.Column('security_events', sa.Integer(), nullable=True),
    sa.Column('threat_score', sa.Float(), nullable=True),
    sa.Column('alert_count', sa.Integer(), nullable=True),
    sa.Column('critical_alerts', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_system_health_score', 'system_health', ['health_score'], unique=False)
    op.create_index('idx_system_health_status', 'system_health', ['overall_status'], unique=False)
    op.create_index('idx_system_health_timestamp', 'system_health', ['timestamp'], unique=False)
    op.create_index(op.f('ix_system_health_health_score'), 'system_health', ['health_score'], unique=False)
    op.create_index(op.f('ix_system_health_id'), 'system_health', ['id'], unique=False)
    op.create_index(op.f('ix_system_health_overall_status'), 'system_health', ['overall_status'], unique=False)
    op.create_index(op.f('ix_system_health_timestamp'), 'system_health', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=100), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_attempts', sa.Integer(), nullable=False),
    sa.Column('last_delivery_attempt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_channels', sa.JSON(), nullable=True),
    sa.Column('threat_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alerts_created_at', 'alerts', ['created_at'], unique=False)
    op.create_index('idx_alerts_severity', 'alerts', ['severity'], unique=False)
    op.create_index('idx_alerts_source', 'alerts', ['source'], unique=False)
    op.create_index('idx_alerts_type_status', 'alerts', ['alert_type', 'status'], unique=False)
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_source'), 'alerts', ['source'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKDAYS', 'WEEKENDS', 'WEEKLY', 'MONTHLY', 'CUSTOM', name='reminderfrequency'), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('custom_days', sa.String(), nullable=True),
    sa.Column('user_id', UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_id'), 'reminders', ['id'], unique=False)
    op.create_index(op.f('ix_reminders_user_id'), 'reminders', ['user_id'], unique=False)
    op.create_table('secret_tags',
    sa.Column('tag_id', sa.LargeBinary(length=16), nullable=False),
    sa.Column('user_id', UUID(), nullable=False),
    sa.Column('salt', sa.LargeBinary(length=16), nullable=False),
    sa.Column('verifier_kv', sa.LargeBinary(length=32), nullable=False),
    sa.Column('opaque_envelope', sa.LargeBinary(), nullable=False),
    sa.Column('tag_name', sa.String(length=100), nullable=False),
    sa.Column('color_code', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_index('idx_secret_tags_tag_lookup', 'secret_tags', ['tag_id'], unique=False)
    op.create_index('idx_secret_tags_user_id', 'secret_tags', ['user_id'], unique=False)
    op.create_index(op.f('ix_secret_tags_user_id'), 'secret_tags', ['user_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('user_id', UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_user_id'), 'tags', ['user_id'], unique=False)
    op.create_table('alert_escalations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('escalation_reason', sa.String(length=255), nullable=False),
    sa.Column('escalation_action', sa.String(length=100), nullable=False),
    sa.Column('escalation_successful', sa.Boolean(), nullable=True),
    sa.Column('escalation_message', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_escalations_alert_id', 'alert_escalations', ['alert_id'], unique=False)
    op.create_index('idx_alert_escalations_level', 'alert_escalations', ['escalation_level'], unique=False)
    op.create_index(op.f('ix_alert_escalations_alert_id'), 'alert_escalations', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_escalations_id'), 'alert_escalations', ['id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('entry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('secret_tag_id', sa.LargeBinary(length=16), nullable=True),
    sa.Column('encrypted_content', sa.LargeBinary(), nullable=True),
    sa.Column('wrapped_key', sa.LargeBinary(), nullable=True),
    sa.Column('encryption_iv', sa.LargeBinary(), nullable=True),
    sa.Column('wrap_iv', sa.LargeBinary(), nullable=True),
    sa.Column('user_id', UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['secret_tag_id'], ['secret_tags.tag_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_id'), 'journal_entries', ['id'], unique=False)
    op.create_index(op.f('ix_journal_entries_secret_tag_id'), 'journal_entries', ['secret_tag_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_user_id'), 'journal_entries', ['user_id'], unique=False)
    op.create_table('wrapped_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.LargeBinary(length=16), nullable=False),
    sa.Column('vault_id', sa.String(length=36), nullable=False),
    sa.Column('wrapped_key', sa.LargeBinary(length=40), nullable=False),
    sa.Column('key_purpose', sa.String(length=50), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['secret_tags.tag_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wrapped_keys_tag_id', 'wrapped_keys', ['tag_id'], unique=False)
    op.create_index('idx_wrapped_keys_vault_id', 'wrapped_keys', ['vault_id'], unique=False)
    op.create_index(op.f('ix_wrapped_keys_tag_id'), 'wrapped_keys', ['tag_id'], unique=False)
    op.create_index(op.f('ix_wrapped_keys_vault_id'), 'wrapped_keys', ['vault_id'], unique=False)
    op.create_table('journal_entry_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entry_tags_id'), 'journal_entry_tags', ['id'], unique=False)
    op.create_table('vault_blobs',
    sa.Column('vault_id', sa.String(length=36), nullable=False),
    sa.Column('object_id', sa.String(length=36), nullable=False),
    sa.Column('wrapped_key_id', sa.String(length=36), nullable=False),
    sa.Column('iv', sa.LargeBinary(length=12), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('auth_tag', sa.LargeBinary(length=16), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('content_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wrapped_key_id'], ['wrapped_keys.id'], ),
    sa.PrimaryKeyConstraint('vault_id', 'object_id')
    )
    op.create_index('idx_vault_blobs_vault_id', 'vault_blobs', ['vault_id'], unique=False)
    op.create_index('idx_vault_blobs_wrapped_key', 'vault_blobs', ['wrapped_key_id'], unique=False)
    op.create_index(op.f('ix_vault_blobs_wrapped_key_id'), 'vault_blobs', ['wrapped_key_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vault_blobs_wrapped_key_id'), table_name='vault_blobs')
    op.drop_index('idx_vault_blobs_wrapped_key', table_name='vault_blobs')
    op.drop_index('idx_vault_blobs_vault_id', table_name='vault_blobs')
    op.drop_table('vault_blobs')
    op.drop_index(op.f('ix_journal_entry_tags_id'), table_name='journal_entry_tags')
    op.drop_table('journal_entry_tags')
    op.drop_index(op.f('ix_wrapped_keys_vault_id'), table_name='wrapped_keys')
    op.drop_index(op.f('ix_wrapped_keys_tag_id'), table_name='wrapped_keys')
    op.drop_index('idx_wrapped_keys_vault_id', table_name='wrapped_keys')
    op.drop_index('idx_wrapped_keys_tag_id', table_name='wrapped_keys')
    op.drop_table('wrapped_keys')
    op.drop_index(op.f('ix_journal_entries_user_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_secret_tag_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_alert_escalations_id'), table_name='alert_escalations')
    op.drop_index(op.f('ix_alert_escalations_alert_id'), table_name='alert_escalations')
    op.drop_index('idx_alert_escalations_level', table_name='alert_escalations')
    op.drop_index('idx_alert_escalations_alert_id', table_name='alert_escalations')
    op.drop_table('alert_escalations')
    op.drop_index(op.f('ix_tags_user_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_secret_tags_user_id'), table_name='secret_tags')
    op.drop_index('idx_secret_tags_user_id', table_name='secret_tags')
    op.drop_index('idx_secret_tags_tag_lookup', table_name='secret_tags')
    op.drop_table('secret_tags')
    op.drop_index(op.f('ix_reminders_user_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_id'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_source'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_index('idx_alerts_type_status', table_name='alerts')
    op.drop_index('idx_alerts_source', table_name='alerts')
    op.drop_index('idx_alerts_severity', table_name='alerts')
    op.drop_index('idx_alerts_created_at', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_health_timestamp'), table_name='system_health')
    op.drop_index(op.f('ix_system_health_overall_status'), table_name='system_health')
    op.drop_index(op.f('ix_system_health_id'), table_name='system_health')
    op.drop_index(op.f('ix_system_health_health_score'), table_name='system_health')
    op.drop_index('idx_system_health_timestamp', table_name='system_health')
    op.drop_index('idx_system_health_status', table_name='system_health')
    op.drop_index('idx_system_health_score', table_name='system_health')
    op.drop_table('system_health')
    op.drop_index(op.f('ix_service_health_timestamp'), table_name='service_health')
    op.drop_index(op.f('ix_service_health_status'), table_name='service_health')
    op.drop_index(op.f('ix_service_health_service_name'), table_name='service_health')
    op.drop_index(op.f('ix_service_health_id'), table_name='service_health')
    op.drop_index('idx_service_health_status', table_name='service_health')
    op.drop_index('idx_service_health_service_timestamp', table_name='service_health')
    op.drop_table('service_health')
    op.drop_index(op.f('ix_security_metrics_window_start'), table_name='security_metrics')
    op.drop_index(op.f('ix_security_metrics_window_end'), table_name='security_metrics')
    op.drop_index(op.f('ix_security_metrics_metric_name'), table_name='security_metrics')
    op.drop_index('idx_metrics_type_time', table_name='security_metrics')
    op.drop_index('idx_metrics_name_window', table_name='security_metrics')
    op.drop_table('security_metrics')
    op.drop_index(op.f('ix_security_audit_logs_user_id_hash'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_timestamp'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_severity'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_session_id_hash'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_event_type'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_event_category'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_correlation_id'), table_name='security_audit_logs')
    op.drop_index('idx_audit_user_timestamp', table_name='security_audit_logs')
    op.drop_index('idx_audit_timestamp', table_name='security_audit_logs')
    op.drop_index('idx_audit_event_type_timestamp', table_name='security_audit_logs')
    op.drop_index('idx_audit_correlation_id', table_name='security_audit_logs')
    op.drop_index('idx_audit_category_severity', table_name='security_audit_logs')
    op.drop_table('security_audit_logs')
    op.drop_index(op.f('ix_security_alerts_user_id_hash'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_status'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_severity'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_first_seen'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_correlation_id'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_alert_type'), table_name='security_alerts')
    op.drop_index('idx_alerts_user_time', table_name='security_alerts')
    op.drop_index('idx_alerts_type_severity', table_name='security_alerts')
    op.drop_index('idx_alerts_status_time', table_name='security_alerts')
    op.drop_table('security_alerts')
    op.drop_index(op.f('ix_opaque_sessions_user_id'), table_name='opaque_sessions')
    op.drop_index(op.f('ix_opaque_sessions_tag_id'), table_name='opaque_sessions')
    op.drop_index('idx_opaque_sessions_user_id', table_name='opaque_sessions')
    op.drop_index('idx_opaque_sessions_expires_at', table_name='opaque_sessions')
    op.drop_table('opaque_sessions')
    op.drop_index(op.f('ix_monitoring_metrics_timestamp'), table_name='monitoring_metrics')
    op.drop_index(op.f('ix_monitoring_metrics_metric_type'), table_name='monitoring_metrics')
    op.drop_index(op.f('ix_monitoring_metrics_metric_source'), table_name='monitoring_metrics')
    op.drop_index(op.f('ix_monitoring_metrics_metric_name'), table_name='monitoring_metrics')
    op.drop_index(op.f('ix_monitoring_metrics_id'), table_name='monitoring_metrics')
    op.drop_index('idx_monitoring_metrics_type', table_name='monitoring_metrics')
    op.drop_index('idx_monitoring_metrics_source', table_name='monitoring_metrics')
    op.drop_index('idx_monitoring_metrics_name_timestamp', table_name='monitoring_metrics')
    op.drop_table('monitoring_metrics')
    op.drop_index(op.f('ix_monitoring_dashboards_id'), table_name='monitoring_dashboards')
    op.drop_index(op.f('ix_monitoring_dashboards_dashboard_name'), table_name='monitoring_dashboards')
    op.drop_index('idx_monitoring_dashboards_name', table_name='monitoring_dashboards')
    op.drop_index('idx_monitoring_dashboards_active', table_name='monitoring_dashboards')
    op.drop_table('monitoring_dashboards')
    op.drop_index(op.f('ix_monitoring_configuration_id'), table_name='monitoring_configuration')
    op.drop_index(op.f('ix_monitoring_configuration_config_key'), table_name='monitoring_configuration')
    op.drop_index(op.f('ix_monitoring_configuration_config_category'), table_name='monitoring_configuration')
    op.drop_index('idx_monitoring_config_key', table_name='monitoring_configuration')
    op.drop_index('idx_monitoring_config_category', table_name='monitoring_configuration')
    op.drop_table('monitoring_configuration')
    op.drop_index(op.f('ix_alert_rules_rule_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_id'), table_name='alert_rules')
    op.drop_index('idx_alert_rules_severity', table_name='alert_rules')
    op.drop_index('idx_alert_rules_enabled', table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_alert_channels_id'), table_name='alert_channels')
    op.drop_index(op.f('ix_alert_channels_channel_type'), table_name='alert_channels')
    op.drop_index(op.f('ix_alert_channels_channel_name'), table_name='alert_channels')
    op.drop_index('idx_alert_channels_type', table_name='alert_channels')
    op.drop_index('idx_alert_channels_enabled', table_name='alert_channels')
    op.drop_table('alert_channels')
    # ### end Alembic commands ###
