"""Implement secret tags system and remove hidden mode

Revision ID: 6ec9d01acd9d
Revises: f6153878ca90
Create Date: 2025-06-07 22:23:46.550241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ec9d01acd9d'
down_revision = 'f6153878ca90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Clean up existing hidden entries before schema changes
    # Since these are test entries and user requested removal
    connection = op.get_bind()
    
    # Delete all hidden entries and their associated data
    connection.execute(sa.text("""
        DELETE FROM journal_entry_tags 
        WHERE entry_id IN (
            SELECT id FROM journal_entries WHERE is_hidden = true
        )
    """))
    
    connection.execute(sa.text("""
        DELETE FROM journal_entries WHERE is_hidden = true
    """))
    
    print("✅ Cleaned up existing hidden entries")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secret_tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('color_code', sa.String(length=7), nullable=False),
    sa.Column('created_at_client', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tag_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secret_tags_id'), 'secret_tags', ['id'], unique=False)
    op.create_index(op.f('ix_secret_tags_tag_hash'), 'secret_tags', ['tag_hash'], unique=True)
    op.add_column('journal_entries', sa.Column('secret_tag_id', sa.String(length=36), nullable=True))
    op.add_column('journal_entries', sa.Column('secret_tag_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_journal_entries_secret_tag_hash'), 'journal_entries', ['secret_tag_hash'], unique=False)
    op.create_index(op.f('ix_journal_entries_secret_tag_id'), 'journal_entries', ['secret_tag_id'], unique=False)
    op.drop_column('journal_entries', 'is_hidden')
    op.drop_constraint('journal_entry_tags_entry_id_fkey', 'journal_entry_tags', type_='foreignkey')
    op.create_foreign_key(None, 'journal_entry_tags', 'journal_entries', ['entry_id'], ['id'])
    op.drop_column('users', 'panic_phrase_hash')
    op.drop_column('users', 'decoy_phrase_hash')
    op.drop_column('users', 'unlock_phrase_hash')
    # ### end Alembic commands ###
    
    print("✅ Secret tags system implemented successfully")
    print("📋 Migration Summary:")
    print("   • Removed is_hidden concept from journal entries")
    print("   • Added secret_tag_id and secret_tag_hash fields")
    print("   • Created secret_tags table for metadata")
    print("   • Removed server-side phrase storage from users")
    print("   • Cleaned up existing hidden entries")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('unlock_phrase_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('decoy_phrase_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('panic_phrase_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'journal_entry_tags', type_='foreignkey')
    op.create_foreign_key('journal_entry_tags_entry_id_fkey', 'journal_entry_tags', 'journal_entries', ['entry_id'], ['id'], ondelete='CASCADE')
    op.add_column('journal_entries', sa.Column('is_hidden', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_journal_entries_secret_tag_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_secret_tag_hash'), table_name='journal_entries')
    op.drop_column('journal_entries', 'secret_tag_hash')
    op.drop_column('journal_entries', 'secret_tag_id')
    op.drop_index(op.f('ix_secret_tags_tag_hash'), table_name='secret_tags')
    op.drop_index(op.f('ix_secret_tags_id'), table_name='secret_tags')
    op.drop_table('secret_tags')
    # ### end Alembic commands ###
