"""add_consent_audit_fields_to_share_access

Revision ID: 7c39d7b141c7
Revises: add_sharing_tables
Create Date: 2025-08-13 07:43:11.775984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c39d7b141c7'
down_revision = 'add_sharing_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('share_access', sa.Column('consent_timeframe_start', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('share_access', sa.Column('consent_timeframe_end', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('share_access', sa.Column('consent_entry_count', sa.Integer(), nullable=True))
    op.add_column('share_access', sa.Column('consent_acknowledged', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_share_access_id'), 'share_access', ['id'], unique=False)
    op.drop_constraint('share_templates_template_id_key', 'share_templates', type_='unique')
    op.drop_constraint('shares_share_token_key', 'shares', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('shares_share_token_key', 'shares', ['share_token'])
    op.create_unique_constraint('share_templates_template_id_key', 'share_templates', ['template_id'])
    op.drop_index(op.f('ix_share_access_id'), table_name='share_access')
    op.drop_column('share_access', 'consent_acknowledged')
    op.drop_column('share_access', 'consent_entry_count')
    op.drop_column('share_access', 'consent_timeframe_end')
    op.drop_column('share_access', 'consent_timeframe_start')
    # ### end Alembic commands ###
