"""Add phrase-based encryption fields

Revision ID: aabfca44fe72
Revises: 3491d7c81daa
Create Date: 2025-06-14 11:05:28.909839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aabfca44fe72'
down_revision = '3491d7c81daa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entries', sa.Column('wrapped_key', sa.LargeBinary(), nullable=True))
    op.add_column('journal_entries', sa.Column('wrap_iv', sa.LargeBinary(), nullable=True))
    op.create_foreign_key(None, 'journal_entries', 'secret_tags', ['secret_tag_id'], ['id'])
    op.add_column('secret_tags', sa.Column('tag_name', sa.String(length=100), nullable=False))
    op.add_column('secret_tags', sa.Column('phrase_salt', sa.LargeBinary(), nullable=False))
    op.add_column('secret_tags', sa.Column('phrase_hash', sa.String(length=255), nullable=False))
    op.drop_index('ix_secret_tags_tag_hash', table_name='secret_tags')
    op.create_index(op.f('ix_secret_tags_user_id'), 'secret_tags', ['user_id'], unique=False)
    op.drop_column('secret_tags', 'color_code')
    op.drop_column('secret_tags', 'tag_hash')
    op.drop_column('secret_tags', 'is_active')
    op.drop_column('secret_tags', 'created_at_client')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secret_tags', sa.Column('created_at_client', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('secret_tags', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('secret_tags', sa.Column('tag_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('secret_tags', sa.Column('color_code', sa.VARCHAR(length=7), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_secret_tags_user_id'), table_name='secret_tags')
    op.create_index('ix_secret_tags_tag_hash', 'secret_tags', ['tag_hash'], unique=False)
    op.drop_column('secret_tags', 'phrase_hash')
    op.drop_column('secret_tags', 'phrase_salt')
    op.drop_column('secret_tags', 'tag_name')
    op.drop_constraint(None, 'journal_entries', type_='foreignkey')
    op.drop_column('journal_entries', 'wrap_iv')
    op.drop_column('journal_entries', 'wrapped_key')
    # ### end Alembic commands ###
