"""Add OPAQUE server configuration table

Revision ID: e795b20c4fa3
Revises: 714a3380d102
Create Date: 2025-07-19 09:43:43.861824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e795b20c4fa3'
down_revision = '714a3380d102'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opaque_server_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('server_setup', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opaque_server_configs')
    # ### end Alembic commands ###
